spring:
  profiles:
    active: prod

  datasource:
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  flyway:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json

application:
  cors:
    origins: ${CORS_ORIGIN}
  keycloak:
    authorizationUrl: ${AUTHORIZATION_URL}
    tokenUrl: ${TOKEN_URL}
  file:
    uploads:
      media-output-path: ./uploads

server:
  port: 8088