spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

application:
  cors:
    origins: http://localhost:4200
  keycloak:
    authorizationUrl: http://localhost:9090/realms/whatsapp-clone/protocol/openid-connect/auth
    tokenUrl: http://localhost:9090/realms/whatsapp-clone/protocol/openid-connect/token