services:
  wac-api:  # Backend docker image
    container_name: wac-api
    image: sonnyhardy/wac-api:1.0
    restart: always
    ports:
      - 8088:8088
    networks:
      - whatsapp-clone

  wac-ui:        # Frontend docker image
    container_name: wac-ui
    image: sonnyhardy/wac-ui:latest
    restart: always
    ports:
      - 82:80
      - 444:443
    networks:
      - whatsapp-clone

  nginx: # Backend docker image
    container_name: nginx-wac
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/debian/whatsapp-clone/nginx.conf:/etc/nginx/nginx.conf
      - /app/dist/whatsapp-clone-ui/browser:/usr/share/nginx/html
    networks:
      - whatsapp-clone

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.0
    restart: always
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - /home/debian/whatsapp-clone/whatsapp-clone.json:/opt/keycloak/data/import/whatsapp-clone.json
    networks:
      - whatsapp-clone
    command:
      - "start-dev"
      - "--import-realm"

networks:
  whatsapp-clone:
    driver: bridge