services:
  wac-api:  # Backend docker image
    container_name: whatsapp-clone-api
    image: sonnyhardy/wac-api:1.0
    restart: always
    ports:
      - 8088:8088
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - whatsapp-clone

  wac-ui:        # Frontend docker image
    container_name: whatsapp-clone-ui
    image: sonnyhardy/wac-ui:1.0
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /whatsapp-clone/nginx.conf:/etc/nginx/nginx.conf
      #- /home/<username>/whatsapp-clone-frontend:/usr/share/nginx/html
    networks:
      - whatsapp-clone

networks:
  whatsapp-clone:
    driver: bridge